### PR TITLE
Change 

### PR DESCRIPTION
**Pull request by stonecauldron**
Removed SDL_Event\* type as it conflicted with racket's union representations: union-ptr function returns only a _pointer type.

Added an example from lazyfoo tutorial with events

### CODE REVIEW

**Comment by LeifAndersen** [comment]
Out of curiosity, why did you close this?

**Comment by stonecauldron** [comment]
I closed it because the maintainer was not responsive.

**Comment by LeifAndersen** [comment]
Ah, fair, he is that. :(

FWIW, now that this is licensed under MIT, one of us can just fork it and
make that the canonical one. I'll give him a bit to respond to my PR, and
if he doesn't we can switch where its pointed to on the package server.

Also, thanks for the update.

~Leif Andersen

**Comment by stonecauldron** [comment]
No problem,

I actually made a fork a few months ago, here is the link: https://github.com/stonecauldron/racket-sdl

**Comment by LeifAndersen** [comment]
Oh cool. If this does become a thing, do you want to have the canonical
repo?

~Leif Andersen

**Comment by LeifAndersen** [comment]
Okay, apparently I have push access to this repo now.

Cap you explain why you removed SDL_Event*, and replacing it with _pointer, rather then just extending it with define-cpointer-type?

**Comment by stonecauldron** [comment]
Sorry I don't recall the exact reason; it was probably because I could not make the SDL_Event unions to work correctly. But I'm quite the novice with the language so I may have overlooked something.

**Pull request closed without merging**
